version: '3.8'

services:
  cave-plus:
    image: cave-bbc-econet:latest
    container_name: cave-bbc-econet
    ports:
      - "1985:8000"
    volumes:
      - cave-player-data:/app/player_data
    restart: unless-stopped

volumes:
  cave-player-data:
